// Code generated by mockery v2.46.2. DO NOT EDIT.

package mockoauth

import (
	context "context"
	ent "scaffold/ent"

	mock "github.com/stretchr/testify/mock"

	oauth "scaffold/ent/oauth"
)

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, issuer, subject, name, email, avatar
func (_m *MockRepo) CreateUser(ctx context.Context, issuer oauth.Issuer, subject string, name string, email string, avatar string) (*ent.User, error) {
	ret := _m.Called(ctx, issuer, subject, name, email, avatar)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *ent.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oauth.Issuer, string, string, string, string) (*ent.User, error)); ok {
		return rf(ctx, issuer, subject, name, email, avatar)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oauth.Issuer, string, string, string, string) *ent.User); ok {
		r0 = rf(ctx, issuer, subject, name, email, avatar)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oauth.Issuer, string, string, string, string) error); ok {
		r1 = rf(ctx, issuer, subject, name, email, avatar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer oauth.Issuer
//   - subject string
//   - name string
//   - email string
//   - avatar string
func (_e *MockRepo_Expecter) CreateUser(ctx interface{}, issuer interface{}, subject interface{}, name interface{}, email interface{}, avatar interface{}) *MockRepo_CreateUser_Call {
	return &MockRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, issuer, subject, name, email, avatar)}
}

func (_c *MockRepo_CreateUser_Call) Run(run func(ctx context.Context, issuer oauth.Issuer, subject string, name string, email string, avatar string)) *MockRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oauth.Issuer), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepo_CreateUser_Call) Return(_a0 *ent.User, _a1 error) *MockRepo_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateUser_Call) RunAndReturn(run func(context.Context, oauth.Issuer, string, string, string, string) (*ent.User, error)) *MockRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, issuer, subject
func (_m *MockRepo) GetUser(ctx context.Context, issuer oauth.Issuer, subject string) (*ent.User, error) {
	ret := _m.Called(ctx, issuer, subject)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *ent.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oauth.Issuer, string) (*ent.User, error)); ok {
		return rf(ctx, issuer, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oauth.Issuer, string) *ent.User); ok {
		r0 = rf(ctx, issuer, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oauth.Issuer, string) error); ok {
		r1 = rf(ctx, issuer, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockRepo_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer oauth.Issuer
//   - subject string
func (_e *MockRepo_Expecter) GetUser(ctx interface{}, issuer interface{}, subject interface{}) *MockRepo_GetUser_Call {
	return &MockRepo_GetUser_Call{Call: _e.mock.On("GetUser", ctx, issuer, subject)}
}

func (_c *MockRepo_GetUser_Call) Run(run func(ctx context.Context, issuer oauth.Issuer, subject string)) *MockRepo_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oauth.Issuer), args[2].(string))
	})
	return _c
}

func (_c *MockRepo_GetUser_Call) Return(_a0 *ent.User, _a1 error) *MockRepo_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetUser_Call) RunAndReturn(run func(context.Context, oauth.Issuer, string) (*ent.User, error)) *MockRepo_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
