-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "email" character varying NOT NULL, "avatar" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "oauth" table
CREATE TABLE "oauth" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "issuer" character varying NOT NULL, "subject" character varying NOT NULL, "user_auth" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "oauth_users_auth" FOREIGN KEY ("user_auth") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "oauth_issuer_subject" to table: "oauth"
CREATE UNIQUE INDEX "oauth_issuer_subject" ON "oauth" ("issuer", "subject");
