// Code generated by ent, DO NOT EDIT.

package oauth

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauth type in the database.
	Label = "oauth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssuer holds the string denoting the issuer field in the database.
	FieldIssuer = "issuer"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the oauth in the database.
	Table = "oauth"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "oauth"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_auth"
)

// Columns holds all SQL columns for oauth fields.
var Columns = []string{
	FieldID,
	FieldIssuer,
	FieldSubject,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "oauth"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_auth",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Issuer defines the type for the "issuer" enum field.
type Issuer string

// Issuer values.
const (
	IssuerGoogle Issuer = "google"
	IssuerGithub Issuer = "github"
)

func (i Issuer) String() string {
	return string(i)
}

// IssuerValidator is a validator for the "issuer" field enum values. It is called by the builders before save.
func IssuerValidator(i Issuer) error {
	switch i {
	case IssuerGoogle, IssuerGithub:
		return nil
	default:
		return fmt.Errorf("oauth: invalid enum value for issuer field: %q", i)
	}
}

// OrderOption defines the ordering options for the OAuth queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssuer orders the results by the issuer field.
func ByIssuer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuer, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
