// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuth is the predicate function for oauth builders.
type OAuth func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
